// Code generated by 'yaegi extract github.com/pelican/wings/plugins/api'. DO NOT EDIT.

package plugins

import (
	"github.com/pelican/wings/plugins/api"
	"go/constant"
	"go/token"
	"reflect"
	"time"
)

func init() {
	Symbols["github.com/pelican/wings/plugins/api/api"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Allow":                  reflect.ValueOf(api.Allow),
		"AllowCommand":           reflect.ValueOf(api.AllowCommand),
		"AllowFile":              reflect.ValueOf(api.AllowFile),
		"Deny":                   reflect.ValueOf(api.Deny),
		"DenyCommand":            reflect.ValueOf(api.DenyCommand),
		"DenyFile":               reflect.ValueOf(api.DenyFile),
		"DropLine":               reflect.ValueOf(api.DropLine),
		"FileChmod":              reflect.ValueOf(api.FileChmod),
		"FileCompress":           reflect.ValueOf(api.FileCompress),
		"FileCopy":               reflect.ValueOf(api.FileCopy),
		"FileCreateDir":          reflect.ValueOf(api.FileCreateDir),
		"FileDecompress":         reflect.ValueOf(api.FileDecompress),
		"FileDelete":             reflect.ValueOf(api.FileDelete),
		"FileDownload":           reflect.ValueOf(api.FileDownload),
		"FileHandled":            reflect.ValueOf(api.FileHandled),
		"FilePullRemote":         reflect.ValueOf(api.FilePullRemote),
		"FileRead":               reflect.ValueOf(api.FileRead),
		"FileRename":             reflect.ValueOf(api.FileRename),
		"FileUpload":             reflect.ValueOf(api.FileUpload),
		"FileWrite":              reflect.ValueOf(api.FileWrite),
		"JSON":                   reflect.ValueOf(api.JSON),
		"KeepLine":               reflect.ValueOf(api.KeepLine),
		"PowerKill":              reflect.ValueOf(api.PowerKill),
		"PowerRestart":           reflect.ValueOf(api.PowerRestart),
		"PowerStart":             reflect.ValueOf(api.PowerStart),
		"PowerStop":              reflect.ValueOf(api.PowerStop),
		"RewriteCommand":         reflect.ValueOf(api.RewriteCommand),
		"RewriteLine":            reflect.ValueOf(api.RewriteLine),
		"ServerBackupCompleted":  reflect.ValueOf(api.ServerBackupCompleted),
		"ServerBackupRestored":   reflect.ValueOf(api.ServerBackupRestored),
		"ServerCrashed":          reflect.ValueOf(api.ServerCrashed),
		"ServerCreated":          reflect.ValueOf(api.ServerCreated),
		"ServerDeleted":          reflect.ValueOf(api.ServerDeleted),
		"ServerInstallCompleted": reflect.ValueOf(api.ServerInstallCompleted),
		"ServerInstallFailed":    reflect.ValueOf(api.ServerInstallFailed),
		"ServerInstallStarted":   reflect.ValueOf(api.ServerInstallStarted),
		"ServerStateChanged":     reflect.ValueOf(api.ServerStateChanged),
		"ServerTransferComplete": reflect.ValueOf(api.ServerTransferComplete),
		"ServerTransferStarted":  reflect.ValueOf(api.ServerTransferStarted),
		"StateOffline":           reflect.ValueOf(constant.MakeFromLiteral("\"offline\"", token.STRING, 0)),
		"StateRunning":           reflect.ValueOf(constant.MakeFromLiteral("\"running\"", token.STRING, 0)),
		"StateStarting":          reflect.ValueOf(constant.MakeFromLiteral("\"starting\"", token.STRING, 0)),
		"StateStopping":          reflect.ValueOf(constant.MakeFromLiteral("\"stopping\"", token.STRING, 0)),
		"Text":                   reflect.ValueOf(api.Text),
		"Version":                reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),

		// type definitions
		"Allocation":       reflect.ValueOf((*api.Allocation)(nil)),
		"Backup":           reflect.ValueOf((*api.Backup)(nil)),
		"BackupAdapter":    reflect.ValueOf((*api.BackupAdapter)(nil)),
		"BackupKind":       reflect.ValueOf((*api.BackupKind)(nil)),
		"BackupOutcome":    reflect.ValueOf((*api.BackupOutcome)(nil)),
		"BackupPayload":    reflect.ValueOf((*api.BackupPayload)(nil)),
		"BackupRequest":    reflect.ValueOf((*api.BackupRequest)(nil)),
		"BackupResult":     reflect.ValueOf((*api.BackupResult)(nil)),
		"Command":          reflect.ValueOf((*api.Command)(nil)),
		"CommandDirective": reflect.ValueOf((*api.CommandDirective)(nil)),
		"ConfigFile":       reflect.ValueOf((*api.ConfigFile)(nil)),
		"ConsoleDirective": reflect.ValueOf((*api.ConsoleDirective)(nil)),
		"ConsoleLine":      reflect.ValueOf((*api.ConsoleLine)(nil)),
		"ContainerPatch":   reflect.ValueOf((*api.ContainerPatch)(nil)),
		"ContainerSpec":    reflect.ValueOf((*api.ContainerSpec)(nil)),
		"CrashInfo":        reflect.ValueOf((*api.CrashInfo)(nil)),
		"Decision":         reflect.ValueOf((*api.Decision)(nil)),
		"DirEntry":         reflect.ValueOf((*api.DirEntry)(nil)),
		"Events":           reflect.ValueOf((*api.Events)(nil)),
		"Fetcher":          reflect.ValueOf((*api.Fetcher)(nil)),
		"FileAction":       reflect.ValueOf((*api.FileAction)(nil)),
		"FileDirective":    reflect.ValueOf((*api.FileDirective)(nil)),
		"FileEvent":        reflect.ValueOf((*api.FileEvent)(nil)),
		"Files":            reflect.ValueOf((*api.Files)(nil)),
		"Host":             reflect.ValueOf((*api.Host)(nil)),
		"InstallLine":      reflect.ValueOf((*api.InstallLine)(nil)),
		"Job":              reflect.ValueOf((*api.Job)(nil)),
		"Lifecycle":        reflect.ValueOf((*api.Lifecycle)(nil)),
		"LifecycleEvent":   reflect.ValueOf((*api.LifecycleEvent)(nil)),
		"Limits":           reflect.ValueOf((*api.Limits)(nil)),
		"Logger":           reflect.ValueOf((*api.Logger)(nil)),
		"Mount":            reflect.ValueOf((*api.Mount)(nil)),
		"Node":             reflect.ValueOf((*api.Node)(nil)),
		"Panel":            reflect.ValueOf((*api.Panel)(nil)),
		"PowerAction":      reflect.ValueOf((*api.PowerAction)(nil)),
		"Registration":     reflect.ValueOf((*api.Registration)(nil)),
		"Request":          reflect.ValueOf((*api.Request)(nil)),
		"Response":         reflect.ValueOf((*api.Response)(nil)),
		"RestoreWriter":    reflect.ValueOf((*api.RestoreWriter)(nil)),
		"Route":            reflect.ValueOf((*api.Route)(nil)),
		"Server":           reflect.ValueOf((*api.Server)(nil)),
		"Servers":          reflect.ValueOf((*api.Servers)(nil)),
		"Settings":         reflect.ValueOf((*api.Settings)(nil)),
		"SftpAuth":         reflect.ValueOf((*api.SftpAuth)(nil)),
		"Startup":          reflect.ValueOf((*api.Startup)(nil)),
		"StartupPatch":     reflect.ValueOf((*api.StartupPatch)(nil)),
		"Stats":            reflect.ValueOf((*api.Stats)(nil)),
		"Store":            reflect.ValueOf((*api.Store)(nil)),
		"WebsocketMessage": reflect.ValueOf((*api.WebsocketMessage)(nil)),
		"WebsocketReply":   reflect.ValueOf((*api.WebsocketReply)(nil)),

		// interface wrapper definitions
		"_Events":        reflect.ValueOf((*_github_com_pelican_wings_plugins_api_Events)(nil)),
		"_Fetcher":       reflect.ValueOf((*_github_com_pelican_wings_plugins_api_Fetcher)(nil)),
		"_Files":         reflect.ValueOf((*_github_com_pelican_wings_plugins_api_Files)(nil)),
		"_Host":          reflect.ValueOf((*_github_com_pelican_wings_plugins_api_Host)(nil)),
		"_Logger":        reflect.ValueOf((*_github_com_pelican_wings_plugins_api_Logger)(nil)),
		"_Panel":         reflect.ValueOf((*_github_com_pelican_wings_plugins_api_Panel)(nil)),
		"_RestoreWriter": reflect.ValueOf((*_github_com_pelican_wings_plugins_api_RestoreWriter)(nil)),
		"_Servers":       reflect.ValueOf((*_github_com_pelican_wings_plugins_api_Servers)(nil)),
		"_Settings":      reflect.ValueOf((*_github_com_pelican_wings_plugins_api_Settings)(nil)),
		"_Store":         reflect.ValueOf((*_github_com_pelican_wings_plugins_api_Store)(nil)),
	}
}

// _github_com_pelican_wings_plugins_api_Events is an interface wrapper for Events type
type _github_com_pelican_wings_plugins_api_Events struct {
	IValue   interface{}
	WPublish func(uuid string, topic string, data any) error
}

func (W _github_com_pelican_wings_plugins_api_Events) Publish(uuid string, topic string, data any) error {
	return W.WPublish(uuid, topic, data)
}

// _github_com_pelican_wings_plugins_api_Fetcher is an interface wrapper for Fetcher type
type _github_com_pelican_wings_plugins_api_Fetcher struct {
	IValue interface{}
	WDo    func(method string, url string, body []byte, header map[string]string) (int, []byte, error)
}

func (W _github_com_pelican_wings_plugins_api_Fetcher) Do(method string, url string, body []byte, header map[string]string) (int, []byte, error) {
	return W.WDo(method, url, body, header)
}

// _github_com_pelican_wings_plugins_api_Files is an interface wrapper for Files type
type _github_com_pelican_wings_plugins_api_Files struct {
	IValue           interface{}
	WChmod           func(uuid string, path string, mode uint32) error
	WCreateDirectory func(uuid string, path string) error
	WDelete          func(uuid string, path string) error
	WExists          func(uuid string, path string) (bool, error)
	WList            func(uuid string, path string) ([]api.DirEntry, error)
	WRead            func(uuid string, path string) ([]byte, error)
	WRename          func(uuid string, from string, to string) error
	WWrite           func(uuid string, path string, content []byte) error
}

func (W _github_com_pelican_wings_plugins_api_Files) Chmod(uuid string, path string, mode uint32) error {
	return W.WChmod(uuid, path, mode)
}
func (W _github_com_pelican_wings_plugins_api_Files) CreateDirectory(uuid string, path string) error {
	return W.WCreateDirectory(uuid, path)
}
func (W _github_com_pelican_wings_plugins_api_Files) Delete(uuid string, path string) error {
	return W.WDelete(uuid, path)
}
func (W _github_com_pelican_wings_plugins_api_Files) Exists(uuid string, path string) (bool, error) {
	return W.WExists(uuid, path)
}
func (W _github_com_pelican_wings_plugins_api_Files) List(uuid string, path string) ([]api.DirEntry, error) {
	return W.WList(uuid, path)
}
func (W _github_com_pelican_wings_plugins_api_Files) Read(uuid string, path string) ([]byte, error) {
	return W.WRead(uuid, path)
}
func (W _github_com_pelican_wings_plugins_api_Files) Rename(uuid string, from string, to string) error {
	return W.WRename(uuid, from, to)
}
func (W _github_com_pelican_wings_plugins_api_Files) Write(uuid string, path string, content []byte) error {
	return W.WWrite(uuid, path, content)
}

// _github_com_pelican_wings_plugins_api_Host is an interface wrapper for Host type
type _github_com_pelican_wings_plugins_api_Host struct {
	IValue    interface{}
	WEvents   func() api.Events
	WFiles    func() api.Files
	WHTTP     func() api.Fetcher
	WLogger   func() api.Logger
	WNode     func() api.Node
	WPanel    func() api.Panel
	WServers  func() api.Servers
	WSettings func() api.Settings
	WStore    func() api.Store
}

func (W _github_com_pelican_wings_plugins_api_Host) Events() api.Events {
	return W.WEvents()
}
func (W _github_com_pelican_wings_plugins_api_Host) Files() api.Files {
	return W.WFiles()
}
func (W _github_com_pelican_wings_plugins_api_Host) HTTP() api.Fetcher {
	return W.WHTTP()
}
func (W _github_com_pelican_wings_plugins_api_Host) Logger() api.Logger {
	return W.WLogger()
}
func (W _github_com_pelican_wings_plugins_api_Host) Node() api.Node {
	return W.WNode()
}
func (W _github_com_pelican_wings_plugins_api_Host) Panel() api.Panel {
	return W.WPanel()
}
func (W _github_com_pelican_wings_plugins_api_Host) Servers() api.Servers {
	return W.WServers()
}
func (W _github_com_pelican_wings_plugins_api_Host) Settings() api.Settings {
	return W.WSettings()
}
func (W _github_com_pelican_wings_plugins_api_Host) Store() api.Store {
	return W.WStore()
}

// _github_com_pelican_wings_plugins_api_Logger is an interface wrapper for Logger type
type _github_com_pelican_wings_plugins_api_Logger struct {
	IValue interface{}
	WDebug func(msg string)
	WError func(msg string)
	WInfo  func(msg string)
	WWarn  func(msg string)
	WWith  func(fields map[string]any) api.Logger
}

func (W _github_com_pelican_wings_plugins_api_Logger) Debug(msg string) {
	W.WDebug(msg)
}
func (W _github_com_pelican_wings_plugins_api_Logger) Error(msg string) {
	W.WError(msg)
}
func (W _github_com_pelican_wings_plugins_api_Logger) Info(msg string) {
	W.WInfo(msg)
}
func (W _github_com_pelican_wings_plugins_api_Logger) Warn(msg string) {
	W.WWarn(msg)
}
func (W _github_com_pelican_wings_plugins_api_Logger) With(fields map[string]any) api.Logger {
	return W.WWith(fields)
}

// _github_com_pelican_wings_plugins_api_Panel is an interface wrapper for Panel type
type _github_com_pelican_wings_plugins_api_Panel struct {
	IValue   interface{}
	WRequest func(method string, path string, body []byte, header map[string]string) (int, []byte, error)
}

func (W _github_com_pelican_wings_plugins_api_Panel) Request(method string, path string, body []byte, header map[string]string) (int, []byte, error) {
	return W.WRequest(method, path, body, header)
}

// _github_com_pelican_wings_plugins_api_RestoreWriter is an interface wrapper for RestoreWriter type
type _github_com_pelican_wings_plugins_api_RestoreWriter struct {
	IValue    interface{}
	WProgress func(done int64, total int64)
	WWrite    func(path string, content []byte) error
}

func (W _github_com_pelican_wings_plugins_api_RestoreWriter) Progress(done int64, total int64) {
	W.WProgress(done, total)
}
func (W _github_com_pelican_wings_plugins_api_RestoreWriter) Write(path string, content []byte) error {
	return W.WWrite(path, content)
}

// _github_com_pelican_wings_plugins_api_Servers is an interface wrapper for Servers type
type _github_com_pelican_wings_plugins_api_Servers struct {
	IValue        interface{}
	WConsoleWrite func(uuid string, line string) error
	WGet          func(uuid string) (api.Server, bool)
	WList         func() []api.Server
	WPower        func(uuid string, action api.PowerAction) error
	WReadLog      func(uuid string, lines int) ([]string, error)
	WSaveActivity func(uuid string, event string, meta map[string]any) error
	WSendCommand  func(uuid string, command string) error
}

func (W _github_com_pelican_wings_plugins_api_Servers) ConsoleWrite(uuid string, line string) error {
	return W.WConsoleWrite(uuid, line)
}
func (W _github_com_pelican_wings_plugins_api_Servers) Get(uuid string) (api.Server, bool) {
	return W.WGet(uuid)
}
func (W _github_com_pelican_wings_plugins_api_Servers) List() []api.Server {
	return W.WList()
}
func (W _github_com_pelican_wings_plugins_api_Servers) Power(uuid string, action api.PowerAction) error {
	return W.WPower(uuid, action)
}
func (W _github_com_pelican_wings_plugins_api_Servers) ReadLog(uuid string, lines int) ([]string, error) {
	return W.WReadLog(uuid, lines)
}
func (W _github_com_pelican_wings_plugins_api_Servers) SaveActivity(uuid string, event string, meta map[string]any) error {
	return W.WSaveActivity(uuid, event, meta)
}
func (W _github_com_pelican_wings_plugins_api_Servers) SendCommand(uuid string, command string) error {
	return W.WSendCommand(uuid, command)
}

// _github_com_pelican_wings_plugins_api_Settings is an interface wrapper for Settings type
type _github_com_pelican_wings_plugins_api_Settings struct {
	IValue       interface{}
	WAll         func() map[string]any
	WBool        func(key string, fallback bool) bool
	WDuration    func(key string, fallback time.Duration) time.Duration
	WInt         func(key string, fallback int) int
	WString      func(key string, fallback string) string
	WStringSlice func(key string) []string
}

func (W _github_com_pelican_wings_plugins_api_Settings) All() map[string]any {
	return W.WAll()
}
func (W _github_com_pelican_wings_plugins_api_Settings) Bool(key string, fallback bool) bool {
	return W.WBool(key, fallback)
}
func (W _github_com_pelican_wings_plugins_api_Settings) Duration(key string, fallback time.Duration) time.Duration {
	return W.WDuration(key, fallback)
}
func (W _github_com_pelican_wings_plugins_api_Settings) Int(key string, fallback int) int {
	return W.WInt(key, fallback)
}
func (W _github_com_pelican_wings_plugins_api_Settings) String(key string, fallback string) string {
	if W.WString == nil {
		return ""
	}
	return W.WString(key, fallback)
}
func (W _github_com_pelican_wings_plugins_api_Settings) StringSlice(key string) []string {
	return W.WStringSlice(key)
}

// _github_com_pelican_wings_plugins_api_Store is an interface wrapper for Store type
type _github_com_pelican_wings_plugins_api_Store struct {
	IValue      interface{}
	WDelete     func(key string) error
	WGet        func(key string) ([]byte, bool, error)
	WKeys       func(prefix string) ([]string, error)
	WSet        func(key string, value []byte) error
	WSetWithTTL func(key string, value []byte, ttl time.Duration) error
}

func (W _github_com_pelican_wings_plugins_api_Store) Delete(key string) error {
	return W.WDelete(key)
}
func (W _github_com_pelican_wings_plugins_api_Store) Get(key string) ([]byte, bool, error) {
	return W.WGet(key)
}
func (W _github_com_pelican_wings_plugins_api_Store) Keys(prefix string) ([]string, error) {
	return W.WKeys(prefix)
}
func (W _github_com_pelican_wings_plugins_api_Store) Set(key string, value []byte) error {
	return W.WSet(key, value)
}
func (W _github_com_pelican_wings_plugins_api_Store) SetWithTTL(key string, value []byte, ttl time.Duration) error {
	return W.WSetWithTTL(key, value, ttl)
}
